### ISSUE TITLE
Superflous constructor in IsoCoupling

### ISSUE THREAD

**Issue by cerisola** [quantum-exeter/SpiDy.jl#1]
From what I remember of the code you showed me on Friday, the constructor `IsoCoupling(C) = C*I` in the current version of the `IsoCoupling` type:

```Julia
struct IsoCoupling{TT<:Real} <: Coupling
    C::TT
    IsoCoupling(C) = C*I
end
```

should not be there since it is not used for anything in the latest version. Indeed in the notebook where you were trying stuff in the office it shouldn't be there if I recall right.

**Comment by mekise** [comment]
Indeed it remained only in the notebook!
