### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by mdavezac** [quantum-exeter/SpiDy.jl#16]
Submissions to JOSS require some form of community guidelines for contributing to the code.
In general, this takes the form of a `contributing` file as explained [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file), and [here](https://github.com/czbiohub-sf/cerebra/blob/master/docs/CONTRIBUTING.md) is an example of the content of the file.

SpectralDensities.jl will also need one since it is covered in the JOSS publication.

If you want to go further (not required for JOSS) and add a code of conduct, PR and issue templates, github's [community profile page](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-profiles-for-public-repositories) is not bad place to start

**Comment by mekise** [comment]
Thanks, I will go through the community standards soon adding the relative files.

**Comment by mekise** [comment]
All community guidelines documents added with commits 03822d316e5e84e9cd8811f9889d246d35b62d77 a204dc5387340a1616ed9a5069c996f96e3b2eb5 cb3c70afbf2fde344af53f5cbe73f1ebfb2ff149 c8ed2566d4b391dc6c99445539463a1686998117 7c1c0ddc0ea0c52c8cab4f231fdd029172c938c2
