### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by mdavezac** [quantum-exeter/SpiDy.jl#17]
JOSS requires sufficient testing for correctness.
It looks like SpectralDensities.jl tests for quite a few things, but SpiDy.jl only checks the code runs, not that the output is sensible.

It would be good to add a few tests that check output values, preferably some physically significant result, but reproducibility against a specific random seed is also okay.

**Comment by cerisola** [comment]
Unit tests for the dynamics have now been added in 5f3c784b38366250f63eca5c9914081adb710e80:

1. We test the dynamics at $T=0$ with classical noise against an analytical solution that is known for this case.
2. We test the dynamics with non-trivial stochastic noise using a fixed random seed.

I think this addresses the issue raised so I'll go ahead and close the it. Feel free to comment and reopen if you think further testing should be included.
