### ISSUE TITLE
Make default distribution argument of bfield more explicit

### ISSUE THREAD

**Issue by cerisola** [quantum-exeter/SpiDy.jl#2]
Currently, the `bfield` distribution argument takes a default value of `nothing`, i.e.
```Julia
function bfield(N, Δt, J::GenericSD, noise::Noise, distro=nothing)
    if isnothing(distro)
        distro = Normal(0., 1/sqrt(Δt))
    end
   ...
end
```
which is then initialised to a Normal distribution as shown.

Apparently, Julia allows for default arguments to depend on the mandatory values. That is, something like this should work:
```Julia
function bfield(N, Δt, J::GenericSD, noise::Noise, distro=Normal(0., 1/sqrt(Δt)))
   ...
end
```
If possible to do it this way, I think it would be an improvement as it would be clearer to the user what the default of `nothing` is actually doing.

**Comment by mekise** [comment]
Tested and working. Much nicer.
